version: "3.3"

services:
  app:
    container_name: easy_app
    build:
      dockerfile: easy_app.dockerfile
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app:rw
    networks:
      - easy-app-net
    ports:
      - "8899:8899"
    depends_on:
      - redis

  redis:
    container_name: easy_app_redis
    image: redis:alpine
    networks:
      - easy-app-net
    volumes:
      - 'redis:/var/redis'

networks:
  easy-app-net:
    driver: bridge

volumes:
  redis:
